server:
    port: 8080
    tomcat:
        access-log-enabled: true
        access-log-pattern: "%h %l %u %t \"%r\" %s %b %D"
spring:
    jackson:
        serialization:
            write_dates_as_timestamps: false
            write_dates_with_zone_id: true
    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto: none
                show_sql: true
                format_sql: true
                use_sql_comments: true
                jdbc:
                    lob:
                        # Needed to prevent Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented on startup
                        non_contextual_creation: true
            jadira:
                usertype:
                    autoRegisterUserTypes: true
    h2:
        console:
            enabled: true
hibernate:

voicesort:
    deviceSecurityEnabled: false
    maxResults: 8
    ame-api:
        url: http://ame-api-ptest.ap-southeast-2.elasticbeanstalk.com/api/v1/address
    translations:
        alpha,alfa,alford,hey: a
        bravo,be: b
        charlie,see: c
        delta: d
        echo,eco: e
        foxtrot: f
        golf,gold: g
        hotel: h
        india: i
        juliet: j
        kilo,kg: k
        lima,lemur,lena,lina: l
        mike,mic: m
        november: n
        oscar,moscow: o
        papa,piper,harper: p
        tango: t
        quebec: q
        romeo: r
        sierra,ciara: s
        uniform,you: u
        victor,victa: v
        whiskey,whisky: w
        x-ray: x
        yankee: y
        zulu: z
        zero: 0
        one,won: 1
        two,to,too: 2
        three: 3
        four,for: 4
        five: 5
        six: 6
        seven: 7
        eight: 8
        nine: 9
        slash: /
        dash: "-"

---
spring:
    profiles: infra
voicesort:
    ame-api:
        url: http://ame-api-ext.ap-southeast-2.elasticbeanstalk.com/api/address
liquibase:
    contexts: infra
---
spring:
    profiles: dev,dev-postgres
    h2:
        # Connect at /h2-console with JDBC url jdbc:h2:mem:testdb, user sa and no password
        console:
            enabled: true
    thymeleaf:
        cache: false
liquibase:
    contexts: dev
---
spring:
    profiles: dev-postgres
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
---
spring:
    profiles: pdev
    datasource:
        url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
        username: ${RDS_USERNAME}
        password: ${RDS_PASSWORD}
        driver-class-name: org.postgresql.Driver

liquibase:
    contexts: pdev
