server:
    port: 8080
    tomcat:
        access-log-enabled: true
        access-log-pattern: "%h %l %u %t \"%r\" %s %b %D"

spring:
    jackson:
        serialization:
            write_dates_as_timestamps: false
            write_dates_with_zone_id: true
    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto: none
                show_sql: true
                format_sql: true
                use_sql_comments: true
            jadira:
                usertype:
                    autoRegisterUserTypes: true
---
spring:
    profiles: dev
    h2:
        console:
          enabled: true
    thymeleaf:
        cache: false
---
spring:
    profiles: infra

---
spring:
    profiles: pdev
    datasource:
      url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?autoReconnect=true&amp;serverTimezone=UTC
      username: ${RDS_USERNAME}
      password: ${RDS_PASSWORD}
      driver-class-name: com.mysql.jdbc.Driver
