server:
    port: 8080
    tomcat:
        access-log-enabled: true
        access-log-pattern: "%h %l %u %t \"%r\" %s %b %D"

spring:
    jackson:
        serialization:
            write_dates_as_timestamps: false
            write_dates_with_zone_id: true
    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto: none
                show_sql: true
                format_sql: true
                use_sql_comments: true
            jadira:
                usertype:
                    autoRegisterUserTypes: true
voicesort:
    ame-api:
        url: http://ame-api-ext.ap-southeast-2.elasticbeanstalk.com/api/address
    translations:
        alpha,alfa,alford,hey: a
        bravo,be: b
        charlie,see: c
        delta: d
        echo,eco: e
        foxtrot: f
        golf,gold: g
        hotel: h
        india: i
        juliet: j
        kilo,kg: k
        lima,lemur,lena,lina: l
        mike: m
        november: n
        oscar: o
        papa,piper,harper: p
        quebec: q
        romeo: r
        sierra,ciara: s
        tango: t
        uniform,you: u
        victor: v
        whiskey,whisky: w
        x-ray: x
        yankee: y
        zulu: z
        zero: 0
        one,won: 1
        two,to,too: 2
        three: 3
        four,for: 4
        five: 5
        six: 6
        seven: 7
        eight: 8
        nine: 9
        slash: /

---
spring:
    profiles: dev
    h2:
        console:
          enabled: true
    thymeleaf:
        cache: false
---
spring:
    profiles: infra

---
spring:
    profiles: pdev
    datasource:
      url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?autoReconnect=true&amp;serverTimezone=UTC
      username: ${RDS_USERNAME}
      password: ${RDS_PASSWORD}
      driver-class-name: com.mysql.jdbc.Driver
